<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260405015231 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "order" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(255) NOT NULL, total NUMERIC(10, 2) NOT NULL, customer_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, shop_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F52993984D16C4DD ON "order" (shop_id)');
        $this->addSql('CREATE TABLE shop (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE telegram_integration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bot_token VARCHAR(255) NOT NULL, chat_id VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, shop_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4D6BE5084D16C4DD ON telegram_integration (shop_id)');
        $this->addSql('CREATE TABLE telegram_send_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message VARCHAR(255) NOT NULL, status TEXT NOT NULL, error TEXT DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, shop_id INT DEFAULT NULL, order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_77AA2A944D16C4DD ON telegram_send_log (shop_id)');
        $this->addSql('CREATE INDEX IDX_77AA2A948D9F6D38 ON telegram_send_log (order_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_shop_order ON telegram_send_log (shop_id, order_id)');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F52993984D16C4DD FOREIGN KEY (shop_id) REFERENCES shop (id)');
        $this->addSql('ALTER TABLE telegram_integration ADD CONSTRAINT FK_4D6BE5084D16C4DD FOREIGN KEY (shop_id) REFERENCES shop (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE telegram_send_log ADD CONSTRAINT FK_77AA2A944D16C4DD FOREIGN KEY (shop_id) REFERENCES shop (id)');
        $this->addSql('ALTER TABLE telegram_send_log ADD CONSTRAINT FK_77AA2A948D9F6D38 FOREIGN KEY (order_id) REFERENCES "order" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F52993984D16C4DD');
        $this->addSql('ALTER TABLE telegram_integration DROP CONSTRAINT FK_4D6BE5084D16C4DD');
        $this->addSql('ALTER TABLE telegram_send_log DROP CONSTRAINT FK_77AA2A944D16C4DD');
        $this->addSql('ALTER TABLE telegram_send_log DROP CONSTRAINT FK_77AA2A948D9F6D38');
        $this->addSql('DROP TABLE "order"');
        $this->addSql('DROP TABLE shop');
        $this->addSql('DROP TABLE telegram_integration');
        $this->addSql('DROP TABLE telegram_send_log');
    }
}
