# Official documentation
# @see https://nginx.org/en/docs/

# @see https://nginx.org/en/docs/ngx_core_module.html#user
user root;

# @see https://nginx.org/en/docs/ngx_core_module.html#worker_processes
worker_processes 4;

# @see https://nginx.org/en/docs/ngx_core_module.html#worker_processes
pid /var/run/nginx.pid;

# @see https://nginx.org/en/docs/ngx_core_module.html#events
events {
  # @see https://nginx.org/en/docs/ngx_core_module.html#worker_connections
  worker_connections 1024;
}

http {
  # @see https://nginx.org/en/docs/varindex.html
  log_format json escape=json '{'
    '"args": "$args", ' # arguments in the request line
    '"body_bytes_sent": "$body_bytes_sent", ' # number of bytes sent to a client not counting the response header
    '"bytes_sent": "$bytes_sent", ' # the number of bytes sent to a client
    '"connection": "$connection", ' # connection serial number
    '"connection_requests": "$connection_requests", ' # current number of requests made through a connection
    '"connection_time": "$connection_time", ' # connection time in seconds with a milliseconds resolution
    '"hostname": "$hostname", ' # host name
    '"http_referer": "$http_referer", ' # HTTP referer
    '"http_user_agent": "$http_user_agent", ' # HTTP User-Agent
    '"http_x_forwarded_for": "$http_x_forwarded_for", ' # HTTP X-Forwarded-For
    '"msec": "$msec", ' # current time in seconds with the milliseconds resolution
    '"realip_remote_addr": "$realip_remote_addr", ' # keeps the original client address
    '"realip_remote_port": "$realip_remote_port", ' # keeps the original client port
    '"remote_addr": "$remote_addr", ' # client address
    '"remote_port": "$remote_port", ' # client port
    '"remote_user": "$remote_user", ' # user name supplied with the Basic authentication
    '"request": "$request", ' # full original request line
    '"request_id": "$request_id", ' # unique request identifier generated from 16 random bytes, in hexadecimal
    '"request_length": "$request_length", ' # request length (including headers and body)
    '"request_method": "$request_method", ' # request method, usually “GET” or “POST”
    '"request_time": "$request_time", ' # request processing time in seconds with a milliseconds resolution
    '"request_uri": "$request_uri", ' # full original request URI
    '"scheme": "$scheme", ' # request scheme, “http” or “https”
    '"server_name": "$server_name", ' # name of the server which accepted a request
    '"server_protocol": "$server_protocol", ' # request protocol, usually “HTTP/1.0”, “HTTP/1.1”, “HTTP/2.0”, or “HTTP/3.0”
    '"ssl_cipher": "$ssl_cipher", ' # returns the name of the cipher used for an established SSL connection
    '"ssl_protocol": "$ssl_protocol", ' # returns the protocol of an established SSL connection
    '"status": "$status", ' # response status code
    '"time_iso8601": "$time_iso8601" ' # local time in the ISO 8601 standard format
    '}';

  # @see https://nginx.org/en/docs/http/ngx_http_log_module.html#access_log
  access_log /var/log/nginx/nginx-access.log json;

  # @see https://nginx.org/en/docs/ngx_core_module.html#error_log
  error_log /var/log/nginx/nginx-error.log warn;

  # @see https://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens
  server_tokens off;

  # @see https://nginx.org/en/docs/http/ngx_http_core_module.html#sendfile
  sendfile on;

  # @see https://nginx.org/en/docs/http/ngx_http_charset_module.html#charset
  charset utf-8;

  # @see https://nginx.org/en/docs/ngx_core_module.html#include
  include /etc/nginx/mime.types;

  # @see https://nginx.org/en/docs/ngx_core_module.html#include
  include /etc/nginx/conf.d/*.conf;
}
